---
title: "Data Import"
output: github_document
---

```{r setup}
library(tidyverse)
library(readxl)
library(haven)
```

## Read in some data

Read in the litters dataset.

```{r}
litters_df = read_csv("data/FAS_litters.csv")
litters_df = janitor::clean_names(litters_df)

pups_df = read_csv("data/FAS_pups.csv")
pups_df = janitor::clean_names(pups_df)
```


## `select`

Let's select some columns

```{r}
select(litters_df, group, litter_number)
select(litters_df, group, gd0_weight, gd18_weight)

select(litters_df, group, gd0_weight:gd_of_birth)
select(litters_df, group, starts_with("pups"))

select(litters_df, -litter_number)

select(litters_df, GROUP = group, litter_number)

rename(litters_df, GROUP = group)

select(litters_df, litter_number, everything())

relocate(litters_df, litter_number)

select(pups_df, litter_number, sex, pd_ears)

pull(litters_df, group)
```


## `filter`

Let's get rid of rows...

```{r}
filter(litters_df, gd_of_birth == 20)

filter(litters_df, group == "Con7")

filter(litters_df, gd0_weight < 23)

filter(litters_df, pups_survive != 4)

filter(litters_df, !(group == "Con7"))

filter(litters_df, group %in% c("Con7", "Con 8"))

filter(litters_df, group == "Con7", gd_of_birth == 20)

filter(litters_df, group == "Con7" | gd_of_birth == 20)
### | this or this to be true
### & this and this to be true

drop_na(litters_df)
drop_na(litters_df, gd0_weight)
```



## Take a look at the data

Printing in the console.

```{r}
litters_df
```

```{r}
head(litters_df)
tail(litters_df)
```

```{r}
skimr::skim(litters_df)
```


## Options to read_csv

Check out `?read_csv()` for more information.

```{r}
litters_df = read_csv("data/FAS_litters.csv", skip = 10, col_names = FALSE)
```

```{r}
litters_df = read_csv("data/FAS_litters.csv", na = c("", "NA", ".", 999))
```


## Other file format

Read in an excel file.

```{r}
mlb_df = read_excel("data/mlb11.xlsx", range = "A1:F7")
mlb_df
```

Read in a SAS file.

```{r}
pulse_df = read_sas("data/public_pulse_data.sas7bdat")
pulse_df
```


## Comparison with Base R

what about `read.csv` ...?

```{r}
litters_base = read.csv("data/FAS_litters.csv")
litters_readr = read_csv("data/FAS_litters.csv")

litters_base
litters_readr
```

## Exporting data

Export the mlb sub-table.

```{r}
write_csv(mlb_df, "data/mlb_subtable.csv")
```

